In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# x : [공부한 시간, 출석일수]

xdata = [[1,3], [2,2], [3,1], [4,6], [5,5], [6,4]]
ydata = [[0], [0], [0], [1], [1], [1]] # 0이면 불합격, 1이면 합격

In [3]:
x = tf.placeholder( tf.float32, shape=[None,2])
y = tf.constant( ydata, tf.float32)

In [4]:
w = tf.Variable( tf.random_uniform([2,1]) )
b = tf.Variable( tf.random_uniform([1]) )

In [5]:
# z는 연속된 데이터
z = tf.matmul(x,w) + b

# sigmoid 통과하면 0과 1로 도출됨
hx = tf.nn.sigmoid( z ) # 0~1사이의 값

In [7]:
# tensor에서 로그 함수 제공
# 오타 유의

cost_i = y*(-tf.log(hx)) + (1-y)*(-tf.log(1-hx))
cost = tf.reduce_mean( cost_i )

In [8]:
optimizer = tf.train.AdamOptimizer( 0.1 ) 
train = optimizer.minimize( cost )

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [10]:
for i in range(1000) :
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 1.1577018
1 0.9441089
2 0.75690705
3 0.61844486
4 0.5654854
5 0.61593384
6 0.6959421
7 0.72251314
8 0.6898094
9 0.625603
10 0.56028795
11 0.5148222
12 0.495131
13 0.49470723
14 0.5026912
15 0.5100466
16 0.51147
17 0.5049737
18 0.49094084
19 0.47131228
20 0.44896618
21 0.42717588
22 0.4089998
23 0.39652595
24 0.39009717
25 0.38795587
26 0.3868301
27 0.38343152
28 0.37600303
29 0.3649206
30 0.3521081
31 0.33982953
32 0.32964322
33 0.3219831
34 0.31634548
35 0.3117647
36 0.3072693
37 0.3021711
38 0.29617494
39 0.28935644
40 0.2820597
41 0.27475592
42 0.26789525
43 0.26177874
44 0.25648233
45 0.25185227
46 0.24757944
47 0.24332559
48 0.23885043
49 0.23408483
50 0.22912388
51 0.22415666
52 0.21937434
53 0.21490073
54 0.2107656
55 0.2069183
56 0.20326412
57 0.19970371
58 0.19616307
59 0.19260806
60 0.1890441
61 0.18550546
62 0.18203866
63 0.17868634
64 0.17547469
65 0.17240798
66 0.16947049
67 0.16663389
68 0.1638672
69 0.16114655
70 0.15846005
71 0.15580861
72 0.15320246
73 0.15065522
74 

In [11]:
sess.run(w)

array([[1.9343281],
       [1.9330056]], dtype=float32)

In [12]:
sess.run(b)

array([-13.120143], dtype=float32)

In [16]:
result = sess.run(hx, {x:[[3,5]]})

In [17]:
result > 0.5

array([[ True]])

In [18]:
# cast함수 : true인 경우 1, false인 경우 0으로 출력

t = tf.cast( result > 0.5, dtype=tf.int32 )
sess.run(t)

array([[1]])

In [27]:
# 전체 데이터 예측; x:6x2 *(matmul)* w:2x1 -> 6x1 행렬

h = sess.run(hx, {x:xdata})
h

array([[0.00455575],
       [0.00456176],
       [0.00456776],
       [0.9980052 ],
       [0.99800783],
       [0.99801046]], dtype=float32)

In [25]:
ydata

[[0], [0], [0], [1], [1], [1]]

In [26]:
(h > 0.5) == ydata
# True는 1, False는 0이므로  

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [29]:
((h > 0.5) == ydata).mean() # 정확도를 의미 => 1.0 = 100퍼센트

1.0

In [30]:
h

array([[0.00455575],
       [0.00456176],
       [0.00456776],
       [0.9980052 ],
       [0.99800783],
       [0.99801046]], dtype=float32)

In [38]:
# y가 float로 되어 있음

predict = tf.cast(h>0.5, dtype = tf.float32)

# sess.run(predict)
e = tf.equal(predict, y) # predict == y랑 같다

m = tf.reduce_mean( tf.cast(e, dtype=tf.float32))

sess.run(m) # 1.0 -> 예측값 100퍼센트

1.0

In [39]:
predict = tf.cast(h>0.5, dtype = tf.float32)

m = tf.reduce_mean( tf.cast(tf.equal(predict, y), dtype=tf.float32))

sess.run(m) # 1.0 -> 예측값 100퍼센트

1.0

In [40]:
sess.run(predict)

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)